---
- hosts: all
  name: ensure connectivity to all hosts
  tasks:
    - action: ping

- hosts: nagios-server
  roles:
    - postfix

- hosts: nagios-clients
  roles:
    - nagios-client

# - include: nagios-server.yml
# - include: nagios-clients.yml

