---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  name: ensure connectivity to all hosts
  tasks:
    - action: ping

- hosts: nagios-server
  roles:
    - nagios-server
    - postfix

- hosts: nagios-clients
  roles:
    - nagios-client
